### PR TITLE
[PLAT-260] Add jet code samples

### PR DESCRIPTION
**Pull request by ufukyilmaz**
This pr adds jet code samples into hazelcast-code-samples with
preserving the commit history of jet-examples. It includes lots of minor
updates into jet code samples to adjust platform changes.
These updates are:
- replaced `Jet` static factory method usages with `Hazelcast` ones and 
then get `JetService` from the created `HazelcastInstance`.
- used `HazelcastInstance` instead of `JetInstance` while getting data
structures or making cluster operations, by replacing `jet.getXXX()`
occurrences with `hz.getXXX()`.
- removed jet spring code samples for future consideration. 
- changed the package names of jet code samples from
`com.hazelcast.jet.examples.*` into `com.hazelcast.samples.jet.*`.
- renamed imdg-connectors module as hazelcast-connectors. Also, made
 lots of minor changes to make these code samples run.
 
You can look at the jenkins jobs testing this branch here: http://jenkins.hazelcast.com/view/Hazelcast%20-%20Code%20Samples/.

### CODE REVIEW

**Comment by ufukyilmaz** [comment]
You can look at the jenkins jobs testing these branch here: http://jenkins.hazelcast.com/view/Hazelcast%20-%20Code%20Samples/

**Comment by mmedenjak** [comment]
@frant-hartm @gurbuzali can you take a look?

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by olukas** [comment]
run-lab-run

**Comment by ufukyilmaz** [comment]
I rebased the pr's branch on the current master

**Comment by ufukyilmaz** [comment]
Since we will merge the commits without squash, I will squash the commits added in this pr. It would be better if you post a review instead of adding a commit yourself.

**Review by jbartok — APPROVED** [review]

**Review by gurbuzali — APPROVED** [review]

**Pull request merged**
