### PR TITLE
initial commit of Hazelcast mongodb 3.x integration example

### PR DESCRIPTION
**Pull request by gAmUssA**
Please, review and merge.

### CODE REVIEW

**Comment by muratayan** [comment]
Looks good and clean :+1:

**Comment by mesutcelik** [comment]
Hi @gAmUssA ,

We already have mongo integration as [spring-data project](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/spring-data-integration/src/main/java/com/hazelcast/spring/mongodb). Do you think we should keep and maintain both?

**Comment by gAmUssA** [comment]
@mesutcelik Yes, we should keep both.

- this PR uses mongodb driver 3.x (example with spring-data uses 2.x.
Potentially it can be upgraded).
- not every customer has spring-data-mongo in their projects. mongodb
driver is more common.
- I have Hazelcast for MongoDB users blog post coming. I don't want to
overcomplicate example implementation.

If you have concerns, please, talk to @fuadm.

Thank you

On Wed, Nov 11, 2015 at 6:59 AM Mesut Celik <notifications@github.com>
wrote:

> Hi @gAmUssA <https://github.com/gAmUssA> ,
>
> We already have mongo integration as spring-data project
> <https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/spring-data-integration/src/main/java/com/hazelcast/spring/mongodb>.
> Do you think we should keep and maintain both?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast-code-samples/pull/74#issuecomment-155756863>
> .
>
-- 
*Viktor Gamov*
*Senior Solution Architect*
Hazelcast | Open source in-memory data grid
275 7th Ave, New York, NY 10001 USA
@gamussa
+1 (201) 355-6226

**Comment by mesutcelik** [comment]
:+1:

**Comment by mesutcelik** [comment]
@gAmUssA ,
Can you check that one? 
`mvn clean install` gives following error.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project mongodb-integration: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
```

**Comment by gAmUssA** [comment]
fixed in f77c8c1.

PR #77

**Pull request merged**
