### PR TITLE
Update POM version to 5.3.7-SNAPSHOT [HZ-4188][5.3.7]

### PR DESCRIPTION
**Pull request by nishaatr**
Preparing 5.3.7 release branch created manually from v5.3.6 tag

Fixes: [HZ-4188]

[HZ-4188]: https://hazelcast.atlassian.net/browse/HZ-4188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ldziedziul — APPROVED** [review]

**Review by olukas — APPROVED** [review]

**Comment by nishaatr** [comment]
run-lab-run

**Comment by nishaatr** [comment]
run-lab-run

**Comment by nishaatr** [comment]
run-lab-run

**Comment by nishaatr** [comment]
run-lab-run

**Comment by nishaatr** [comment]
Build is green. 
Had to temporarily change the PR builder to use JDK8. Did the same for 5.2.5 last time
Change reverted back to JDK17
Also, not sure why there are 2 checks show above but they both point to the same PR build so ignoring 

image

**Pull request merged**
