### PR TITLE
Remove Spring Data Integration Code Sample.

### PR DESCRIPTION
**Pull request by leszko**
This Code Sample is related to MongoDB, not Hazelcast. Therefore, I does not make much sense to keep it in our repo. What's more, it's super misleading, because one may think it's related to our mode: spring-data-hazelcast.

### CODE REVIEW

**Comment by mesutcelik** [comment]
That was confusing for me too all the time but removing might not be solution. It is an example of how MapStore/MapLoader is implemented. Maybe renaming could be an option. cc: @jerrinot @mmedenjak

**Comment by leszko** [comment]
@jerrinot @mmedenjak , wdyt?

**Comment by mmedenjak** [comment]
I must say I would like to keep _some_ sample of implementing a map store. Do we have some other sample?

**Comment by mesutcelik** [comment]
There is one under `distributed-map`
https://github.com/hazelcast/hazelcast-code-samples/tree/master/distributed-map/mapstore

Which is waiting another simplification PR
https://github.com/hazelcast/hazelcast-code-samples/pull/198

I think we can move MongoDB and JPAStore into the same place...

**Comment by leszko** [comment]
@mmedenjak , how about keeping only the simplified by @kwart : #198 ? I guess having just one (and the simplest possible) mapstore example is what we need.

**Comment by mmedenjak** [comment]
Sure, if there's another (simplified) example, let's keep that one instead.

**Pull request merged**
