### PR TITLE
Ring buffer store code sample

### PR DESCRIPTION
**Pull request by mmedenjak**
Code sample for ring buffer store

### CODE REVIEW

**Comment by jerrinot** [comment]
@mmedenjak: does the sample use a combination of declarative and programmatic configuration? that's not very clear from a user perspective.

**Comment by mmedenjak** [comment]
I've removed the hazelcast.xml since I believe most examples are Java config based.

**Comment by gAmUssA** [comment]
@mmedenjak xml config should be in examples as well. A lot of people use xml configs. Example should include both. Thank you

**Comment by mmedenjak** [comment]
@gAmUssA Added.

**Pull request merged**
