### PR TITLE
Add ReliableIdGeneratorSample

### PR DESCRIPTION
**Pull request by viliam-durina**

### CODE REVIEW

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Can you please analyse why the code sample isn't picking up the new code changes?

**Comment by viliam-durina** [comment]
I found it: it was picking, but we've changed the package name, so the class `com.hazelcast.core.ReliableIdGenerator` really doesn't exist now.

**Pull request merged**
