### PR TITLE
Added DurableExecutorService code samples

### PR DESCRIPTION
**Pull request by gurbuzali**

### CODE REVIEW

**Comment by gAmUssA** [comment]
:+1:

**Comment by jerrinot** [comment]
:+1:

**Comment by gAmUssA** [comment]
@gurbuzali could you rebase your branch?

**Comment by gAmUssA** [comment]
@gurbuzali any updates on rebase of this?

**Comment by gurbuzali** [comment]
@gAmUssA done

**Comment by gAmUssA** [comment]
Thanks @gurbuzali! Good job with Durable Executor!

**Pull request merged**
