### PR TITLE
JCache usage through HazelcastInstance code sample

### PR DESCRIPTION
**Pull request by serkan-ozal**

### CODE REVIEW

**Comment by emrahkocaman** [comment]
👍 but I've a minor comment. I'd like to see the same 'cache' accessed through JCache API.

**Comment by serkan-ozal** [comment]
@emrahkocaman sure

**Comment by serkan-ozal** [comment]
@emrahkocaman I have updated the code sample by adding code snippet to show retrieving same cache proxy instance through `CacheManager` and `HazelcastInstance`

**Comment by emrahkocaman** [comment]
Thanks @serkan-ozal 👍

**Pull request merged**
