### PR TITLE
Code sample for custom attributes & extractors

### PR DESCRIPTION
**Pull request by tombujok**

### CODE REVIEW

**Comment by pveentjer** [comment]
Does this example make sense? Because you are extracting age, but extracting a regular field from an object was already provided; no need for a custom extractor.

**Comment by tombujok** [comment]
It just shows how to use an extractor. IMHO it doesn't matter that I can extract this field via reflection since I'm extracting under different attribute's name. 
Can change it to ageInMonths and multiply the age by 12. wdyt?

**Comment by pveentjer** [comment]
It is fine. I didn't see that the name of the field doesn't match the query. Can you add a line of comment to the example showing what is being tested so that people like me don't get confused?

**Comment by tombujok** [comment]
Done. I changed it to `ageInMonths` and added a comment.

**Pull request merged**
