### PR TITLE
fixed tenant control samples

### LINKED ISSUE #468: 'SPI: Implementing tenant control 0.1-SNAPSHOT' does not compile
Hello

2 days ago in 2 machines (MacOS and Windows) I did do an update about the source code through Git.
When I execute: `mvn clean compile` in the root project, throws:
```
[INFO] SPI 0.1-SNAPSHOT ................................... SUCCESS [  0.003 s]
[INFO] Discovery SPI 0.1-SNAPSHOT ......................... SUCCESS [  0.110 s]
[INFO] SPI: Split-brain healing 0.1-SNAPSHOT .............. SUCCESS [  0.124 s]
[INFO] SPI: Implementing tenant control 0.1-SNAPSHOT ...... FAILURE [  0.115 s]
[INFO] Transactions 0.1-SNAPSHOT .......................... SKIPPED
[INFO] Transactions - Transaction Basics 0.1-SNAPSHOT ..... SKIPPED
[INFO] Transactions - Transactional Task 0.1-SNAPSHOT ..... SKIPPED
[INFO] Transactions - XA Transaction 0.1-SNAPSHOT ......... SKIPPED
[INFO] Variable replacers 0.1-SNAPSHOT .................... SKIPPED
[INFO] genericRecord 0.1-SNAPSHOT ......................... SKIPPED
[INFO] generic-record-cluster 0.1-SNAPSHOT ................ SKIPPED
[INFO] generic-recod-client 0.1-SNAPSHOT .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 min
[INFO] Finished at: 2020-12-16T10:01:13-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project tenant-control: Compilation failure: Compilation failure: 
[ERROR] /Users/.../hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[9,8] multitenant.MultiTenantControl is not abstract and does not override abstract method clearThreadContext() in com.hazelcast.spi.tenantcontrol.TenantControl
[ERROR] /Users/.../hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[17,5] method does not override or implement a method from a supertype
[ERROR] /Users/.../hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[25,16] incompatible types: multitenant.TenantCloseable cannot be converted to com.hazelcast.spi.tenantcontrol.TenantControl.Closeable
[ERROR] /Users/.../hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[28,5] method does not override or implement a method from a supertype
[ERROR] /Users/.../hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControlFactory.java:[7,8] multitenant.MultiTenantControlFactory is not abstract and does not override abstract method isClassesAlwaysAvailable() in com.hazelcast.spi.tenantcontrol.TenantControlFactory
[ERROR] /Users/.../hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControlFactory.java:[9,5] method does not override or implement a method from a supertype
[ERROR] /Users/.../hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControlFactory.java:[11,33] cannot find symbol
[ERROR]   symbol:   method getDistributedObjectName()
[ERROR]   location: variable event of type com.hazelcast.spi.tenantcontrol.DestroyEventContext
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :tenant-control

```

**Note**: in these 2 machines the repositories were deleted and used `project -> Maven -> Update Project` (it works fine) and then `mvn clean compile` (here fails)

### PR DESCRIPTION
**Pull request by lprimak**
Fixes #468

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
run-lab-run

**Review by vbekiaris — APPROVED** [review]

**Comment by vbekiaris** [comment]
@lprimak thanks for the fix!

**Comment by manueljordan** [comment]
Thanks for the fix!

**Pull request merged**
