### PR TITLE
Add Code Sample for Kubernetes Embedded

### PR DESCRIPTION
**Pull request by leszko**
The simplest application to present how to deploy embedded Hazelcast on Kubernetes. 

I will convert it to a Blog Post when it's merged.

### CODE REVIEW

**Comment by mesutcelik** [comment]
verify

**Comment by mesutcelik** [comment]
Thanks @leszko ,
That is very simple embedded solution for hazelcast usage in k8s. You can consider upgrading hazelcast-kubernetes version to the latest. 👍

**Comment by mesutcelik** [comment]
This is also alternative to maintaining a Dockerfile in Samples. Feel free to consider it.
https://github.com/GoogleContainerTools/jib

**Comment by mesutcelik** [comment]
One more thing to add is if we use 3.11 in the sample. We can consider using `<kubernetes>` goodness in the sample.

**Comment by leszko** [comment]
1. Changed to use JIB, I like it, because the user is not forced to have Docker Engine installed
2. Changed to the latest hazelcast-kubernetes version. 
3. Changed to the new style of configuration (`<kubernetes>`)

I'm merging this PR and will prepare a Blog Post our of that soon.

**Comment by mesutcelik** [comment]
Thanks @leszko !

**Pull request merged**
