### PR TITLE
Hazelcast cluster on Amazon EC2 with Vagrant and Chef

### PR DESCRIPTION
**Pull request by dbrimley**

### CODE REVIEW

**Comment by bilalyasar** [comment]
i reviewed and tried this example.. it looks good. so i am merging it.

**Comment by gAmUssA** [comment]
@dbrimley As a side note, in future, I would recommend to squash all commits into one before PR. So it would be easy in future to rollback in case of a problems. Also it will keep history of master branch clean.

**Comment by mesutcelik** [comment]
:+1:

**Comment by jerrinot** [comment]
+1 to @gAmUssA

**Pull request merged**
