### PR TITLE
Add chemistry example and other modules to pom

### PR DESCRIPTION
**Pull request by neilstevenson**
Include Spark and Spring Data modules in buidl

### CODE REVIEW

**Comment by gAmUssA** [comment]
@Donnerbart excluded those because they require Java 8

**Comment by Donnerbart** [comment]
Yes, unfortunately we have the Java 6 requirement on all builds, so those modules weren't compiling. I tried to make them Java 6 compatible, but that didn't work out. Until we have an official go to change the Java version for the build job, we cannot activate them, otherwise the build job will crash with compile errors.

**Comment by neilstevenson** [comment]
@gAmUssA @gAmUssA  Yeah, makes sense. A `hazelcast-code-samples-java8` would be the way forward, but probably more trouble than benefit.

**Comment by Donnerbart** [comment]
It's "just" some integrations which actually need newer Java versions. All "internal" code samples should be easily compatible with Java 6, since Hazelcast itself is. So maybe we can just allow it for he integration module. If we limit the other modules to Java 6 via Maven, we still should see compile errors due to Java 7/8 usage in the modules, where we don't want to have this.

**Pull request closed without merging**
