### PR TITLE
minimal readmes

### PR DESCRIPTION
**Pull request by ph-hs**
I've added a couple of READMEs. I think y'all should systematically add them to each dir that has a pom file.

### CODE REVIEW

**Comment by gAmUssA** [comment]
@ph-hs kindly update link to current 3.7 or latest-dev docs

**Comment by ph-hs** [comment]
http://docs.hazelcast.org/docs/3.7/manual/ .... 404s

**Comment by gAmUssA** [comment]
3.7 http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#creating-near-cache-for-map 
in 3.8 is has unified section http://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#near-cache <- the latest dev

**Comment by ph-hs** [comment]
My bad. URLs updated as requested.

**Comment by gAmUssA** [comment]
given the fact that samples are built against a snapshot version of Hazelcast, it makes sense to have latest-dev docs link.
2 more things 
- could you squash your commits
- did you have a chance to sign a contributor agreement https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement ?

**Comment by ph-hs** [comment]
I've changed READMEs, but sure, I can sign a CLA later tonight.

**Comment by paul-hammant** [comment]
Me, @ph-hs, on my other account.  I can't enrol in your confluence as there's no enrollment link.

Are you 100% sure you want me to sign a CLA for two small READMEs ?

**Comment by gAmUssA** [comment]
@paul-hammant there is no enrolment via confluence. you need to download the agreement, read it, sign it and send it back.
@enesakar kindly advise if we require contributor agreement for README change

**Comment by enesakar** [comment]
Hi @paul-hammant ; 
I will be nice to have you in our official contributor list if you sign it. So that will also allow your further contributions.

**Comment by Holmistr** [comment]
Closing for inactivity. Please reopen if necessary.

**Comment by paul-hammant** [comment]
I'm going to go out on a limb here and say that those small lines of textual advice posed no IP risk to hazelcast whatsoever, and couldv'e been consumed without a CLA signing and emailing.  Indeed as a proof of record, a "I grant Hazelcast Inc, non-exclusive copyright to the words I wrote in https://github.com/hazelcast/hazelcast-code-samples/pull/141" would be sufficient legally.

**Comment by Holmistr** [comment]
Hi @paul-hammant ,
I totally understand your side. However, we're developers and this legal stuff is beyond us. We have consulted with our legal department many times (e.g. digital signing etc.), but the outcome was always "Make the contributor sign the agreement. Period.". Sorry about that. Is there a possibility about changing your mind? You would make it to our "hall of fame"! :D

**Comment by paul-hammant** [comment]
You could type what I did afresh and 10x better without even copying what I did. Look, let's just leave this closed. I'll unsubscribe the issue

**Pull request closed without merging**
