### PR TITLE
Eurekast

### PR DESCRIPTION
**Pull request by neilstevenson**
We want to squash commits!

### CODE REVIEW

**Comment by gAmUssA** [comment]
@neilstevenson can we squash commit?

**Comment by neilstevenson** [comment]
@gAmUssA Absolutely!

**Comment by gAmUssA** [comment]
I mean, could you squash them @neilstevenson ?

**Comment by Donnerbart** [comment]
There is a squash and merge option on GitHub, but I never used it before. Would be a nice candidate to test it :)

**Comment by neilstevenson** [comment]
@Donnerbart @gAmUssA It's a PR into a branch in the main repo not master, worth a chance at trying the `squash and merge` option to see how good it is

**Comment by Donnerbart** [comment]
What's the difference in which branch you merge, until you use the merge button here on GitHub?

screenshot from 2017-04-12 22-22-47

**Comment by gAmUssA** [comment]
@Donnerbart 🔥! but I would always go with rebase :)

**Comment by Donnerbart** [comment]
@neilstevenson Sorry, I misunderstood your comment (I read quite the opposite of what you've wrote). Sure, we can test it here. I'm especially curious if you can edit the commit message on GitHub.

@gAmUssA I always use rebase locally to update my branch. But to get something into the master branch we are used to use the merge option. Actually a rebase would be nicer in the commit history, but I think that's a bit too late for the main projects now :)

**Comment by neilstevenson** [comment]
@Donnerbart Shall I try it ?

**Comment by Donnerbart** [comment]
Yeah, that would be great :)

**Pull request merged**
