### PR TITLE
Remove eclipse import error and warnings

### PR DESCRIPTION
**Pull request by phelanm**
- Rename .../java/com.hazelcast.spring.cache... to .../java/com/hazelcast/spring/cache/...
- Remove eclipse warnings

### CODE REVIEW

**Comment by catalincapota** [comment]
I second this commit, this module currently cannot compile in eclipse and certain other IDE's due to the folder being named "com.hazelcast.spring.cache" instead of nested folders representing the desired package structure.

**Comment by mdogan** [comment]
:+1:

**Comment by mesutcelik** [comment]
@phelanm ,

Can you please send us Contributor Agreement?
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by gAmUssA** [comment]
@phelanm could you rebase this with the latest chances in master?

**Comment by Holmistr** [comment]
@phelanm Would you be able to pick up the work?

**Comment by Holmistr** [comment]
Hi @phelanm , sorry that this PR got abandoned. I'm closing it now. We would be more than happy to resume it if you would come back to us. Thanks for your effort :)

**Pull request closed without merging**
